# General application settings
replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

# Resource limits and requests for the application pod
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 2
    memory: 2Gi

service:
  type: ClusterIP
  port: 80