---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
 name: c8y-mongodb
 namespace: ${C8Y_ENV_NAMESPACE}
spec:
 values:
    mongoDb:
      type: Standalone
      podSpec:
        podTemplate:
          spec:
            containers:
              - name: mongodb-enterprise-database
                resources:
                  requests:
                    memory: 4Gi
                    cpu: "2"
                  limits:
                    memory: 8Gi
                    cpu: "4"
        persistence:
          single:
            storage: 50Gi
            storageClass: "ebs-gp3"

    opsManager:       
      applicationDatabase:
        podSpec:
          podTemplate:
            spec:
              containers:
                - name: mongod
                  resources:
                    requests:
                      memory: 2Gi
                      cpu: "2.5"
                    limits:
                      memory: 2Gi
                      cpu: "1"
          persistence:
            single:
              storage: 10Gi
              storageClass: "ebs-gp3"
      statefulSet:
        spec:
          template:
            spec:
              containers:
                - name: mongodb-ops-manager
                  resources:
                    requests:
                      memory: 4Gi
                      cpu: "1"
                    limits:
                      memory: 5Gi
                      cpu: "2"
    